use std::path::Path;
use std::fs;
use notify::{Watcher, RecursiveMode, Event};
use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter};
use crate::models::ModpackData;
use crate::importer::import_from_instance;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncedData {
    pub items: Vec<String>,
    pub mechanics: Vec<String>,
    pub detected_mods: Vec<String>,
    pub detected_version: Option<String>,
    pub detected_loader: Option<String>,
}

#[tauri::command]
pub fn setup_autosync(app_handle: AppHandle, export_path: String) -> Result<String, String> {
    let path = Path::new(&export_path);
    if !path.exists() {
        return Err(format!("Path does not exist: {}", export_path));
    }

    let kubejs_server = path.join("kubejs").join("server_scripts");
    fs::create_dir_all(&kubejs_server).map_err(|e| e.to_string())?;

    let sync_script = r#"// SimpleQuestHelper Auto-Sync Script for Minecraft 1.21.1+
// Automatically generated by SimpleQuestHelper

function sqh_do_export() {
    try {
        let itemList = [];

        // Strategy 1: Minecraft 1.21+ BuiltInRegistries (Java reflection, 100% reliable on 1.21.1 NeoForge/Fabric/Forge)
        try {
            let BuiltInRegistries = Java.loadClass('net.minecraft.core.registries.BuiltInRegistries');
            if (BuiltInRegistries && BuiltInRegistries.ITEM) {
                BuiltInRegistries.ITEM.keySet().forEach(function(k) {
                    if (k) itemList.push(String(k));
                });
            }
        } catch (e1) {}

        // Strategy 2: KubeJS Utils Registry
        if (itemList.length === 0 && typeof Utils !== 'undefined' && Utils.getRegistry) {
            try {
                let reg = Utils.getRegistry('minecraft:item') || Utils.getRegistry('item');
                if (reg) {
                    reg.keySet().forEach(function(k) {
                        if (k) itemList.push(String(k));
                    });
                }
            } catch (e2) {}
        }

        // Strategy 3: Item.getList()
        if (itemList.length === 0 && typeof Item !== 'undefined' && Item.getList) {
            try {
                let all = Item.getList();
                for (let i = 0; i < all.length; i++) {
                    let it = all[i];
                    if (it && it.getId) itemList.push(String(it.getId()));
                }
            } catch (e3) {}
        }

        if (itemList.length > 0) {
            // Deduplicate items
            let uniqueItems = Array.from(new Set(itemList));
            JsonIO.write('kubejs/exported/sqh_items.json', { items: uniqueItems });
            console.info('[SimpleQuestHelper] Exported ' + uniqueItems.length + ' items to kubejs/exported/sqh_items.json');
        }
    } catch (err) {
        console.error('[SimpleQuestHelper] Auto-Sync error: ' + err);
    }
}

// Trigger on World Load & on /reload
ServerEvents.loaded(event => {
    sqh_do_export();
});

ServerEvents.recipes(event => {
    sqh_do_export();
});
"#;
    
    fs::write(kubejs_server.join("sqh_autosync.js"), sync_script).map_err(|e| e.to_string())?;

    // Setup watcher in a background thread
    let watch_path = path.join("kubejs").join("exported");
    fs::create_dir_all(&watch_path).ok(); // Ensure it exists before watching

    std::thread::spawn(move || {
        let mut watcher = match notify::recommended_watcher(move |res: notify::Result<Event>| {
            match res {
                Ok(event) => {
                    if event.kind.is_modify() || event.kind.is_create() {
                        let _ = app_handle.emit("sqh-sync-updated", ());
                    }
                },
                Err(e) => println!("Watch error: {:?}", e),
            }
        }) {
            Ok(w) => w,
            Err(e) => {
                println!("Watcher init error: {:?}", e);
                return;
            }
        };

        if let Err(e) = watcher.watch(&watch_path, RecursiveMode::Recursive) {
            println!("Watch path error: {:?}", e);
        }
        
        loop {
            std::thread::sleep(std::time::Duration::from_secs(60));
        }
    });

    Ok("Auto-Sync script created and folder watcher started successfully!".to_string())
}

#[tauri::command]
pub fn import_modpack_project(export_path: String) -> Result<ModpackData, String> {
    crate::logger::log_info(&format!("Starting full modpack import from: {}", export_path));
    let (data, num_chapters, num_quests) = import_from_instance(&export_path)?;
    crate::logger::log_info(&format!("Modpack import finished: {} chapters, {} quests, {} items, {} recipes", 
        num_chapters, num_quests, data.items.len(), data.recipes.len()));
    Ok(data)
}

#[tauri::command]
pub fn get_synced_data(export_path: String) -> Result<SyncedData, String> {
    let base_path = Path::new(&export_path);
    if !base_path.exists() {
        return Err(format!("Path does not exist: {}", export_path));
    }

    let mut items = Vec::new();
    let mut mechanics = vec![
        "minecraft:crafting_shaped".to_string(),
        "minecraft:crafting_shapeless".to_string(),
        "minecraft:smelting".to_string(),
        "minecraft:blasting".to_string(),
        "minecraft:smoking".to_string(),
        "minecraft:stonecutting".to_string(),
        "minecraft:smithing".to_string(),
        "minecraft:campfire_cooking".to_string(),
    ];
    let mut detected_mods = Vec::new();

    // 1. Scan ALL jar files in mods folder
    let mods_path = base_path.join("mods");
    if mods_path.exists() && mods_path.is_dir() {
        if let Ok(entries) = fs::read_dir(mods_path) {
            for entry in entries.flatten() {
                let file_name = entry.file_name().to_string_lossy().to_string();
                let file_lower = file_name.to_lowercase();
                if file_lower.ends_with(".jar") && !file_lower.ends_with(".disabled") {
                    let mod_name = parse_clean_mod_name(&file_name);
                    detected_mods.push(mod_name);

                    // Add known recipes mechanics for key mod categories
                    if file_lower.contains("create") && !file_lower.contains("createdeco") {
                        mechanics.extend(vec![
                            "create:crushing".to_string(),
                            "create:mixing".to_string(),
                            "create:pressing".to_string(),
                            "create:cutting".to_string(),
                            "create:compacting".to_string(),
                            "create:milling".to_string(),
                            "create:splashing".to_string(),
                            "create:deploying".to_string(),
                            "create:sequenced_assembly".to_string(),
                            "create:haunting".to_string(),
                        ]);
                    }
                    if file_lower.contains("mekanism") {
                        mechanics.extend(vec![
                            "mekanism:crushing".to_string(),
                            "mekanism:enriching".to_string(),
                            "mekanism:smelting".to_string(),
                            "mekanism:compressing".to_string(),
                            "mekanism:combining".to_string(),
                            "mekanism:purifying".to_string(),
                            "mekanism:metallurgic_infusing".to_string(),
                            "mekanism:injecting".to_string(),
                            "mekanism:crystallizing".to_string(),
                            "mekanism:dissolution".to_string(),
                        ]);
                    }
                    if file_lower.contains("thermal") {
                        mechanics.extend(vec![
                            "thermal:pulverizer".to_string(),
                            "thermal:furnace".to_string(),
                            "thermal:sawmill".to_string(),
                            "thermal:smelter".to_string(),
                            "thermal:insolator".to_string(),
                            "thermal:centrifuge".to_string(),
                            "thermal:press".to_string(),
                            "thermal:crucible".to_string(),
                            "thermal:chiller".to_string(),
                            "thermal:refinery".to_string(),
                            "thermal:bottler".to_string(),
                        ]);
                    }
                    if file_lower.contains("enderio") {
                        mechanics.extend(vec![
                            "enderio:alloy_smelting".to_string(),
                            "enderio:sag_milling".to_string(),
                            "enderio:slicing".to_string(),
                            "enderio:soul_binding".to_string(),
                        ]);
                    }
                    if file_lower.contains("farmer") && file_lower.contains("delight") {
                        mechanics.extend(vec![
                            "farmersdelight:cooking".to_string(),
                            "farmersdelight:cutting".to_string(),
                        ]);
                    }
                    if file_lower.contains("botania") {
                        mechanics.extend(vec![
                            "botania:petal_apothecary".to_string(),
                            "botania:pure_daisy".to_string(),
                            "botania:mana_infusion".to_string(),
                            "botania:runic_altar".to_string(),
                            "botania:elven_trade".to_string(),
                        ]);
                    }
                    if file_lower.contains("ad_astra") || file_lower.contains("ad-astra") || file_lower.contains("adastra") {
                        mechanics.extend(vec![
                            "ad_astra:compressing".to_string(),
                            "ad_astra:refining".to_string(),
                            "ad_astra:nasa_workbench".to_string(),
                            "ad_astra:oxygen_loading".to_string(),
                        ]);
                    }
                    if file_lower.contains("appliedenergistics2") || file_lower.contains("ae2") {
                        mechanics.extend(vec![
                            "ae2:inscriber".to_string(),
                            "ae2:transform".to_string(),
                            "ae2:matter_cannon".to_string(),
                        ]);
                    }
                    if file_lower.contains("oritech") {
                        mechanics.extend(vec![
                            "oritech:pulverizer".to_string(),
                            "oritech:foundry".to_string(),
                            "oritech:assembler".to_string(),
                            "oritech:atomic_forge".to_string(),
                            "oritech:laser".to_string(),
                            "oritech:centrifuge".to_string(),
                            "oritech:centrifuge_fluid".to_string(),
                            "oritech:particle_collision".to_string(),
                            "oritech:deep_drill".to_string(),
                            "oritech:grinder".to_string(),
                            "oritech:cooler".to_string(),
                            "oritech:fuel_generator".to_string(),
                            "oritech:lava_generator".to_string(),
                        ]);
                    }
                    if file_lower.contains("draconicevolution") || file_lower.contains("draconic") {
                        mechanics.extend(vec![
                            "draconicevolution:fusion_crafting".to_string(),
                            "draconicevolution:awakened_crafting".to_string(),
                        ]);
                    }
                    if file_lower.contains("mysticalagriculture") {
                        mechanics.extend(vec![
                            "mysticalagriculture:infusion".to_string(),
                            "mysticalagriculture:awakening".to_string(),
                            "mysticalagriculture:reprocessor".to_string(),
                        ]);
                    }
                    if file_lower.contains("justdirethings") {
                        mechanics.extend(vec![
                            "justdirethings:gooblock".to_string(),
                            "justdirethings:ferricore".to_string(),
                        ]);
                    }
                    if file_lower.contains("industrialforegoing") {
                        mechanics.extend(vec![
                            "industrialforegoing:dissolution_chamber".to_string(),
                            "industrialforegoing:fluid_extractor".to_string(),
                        ]);
                    }
                    if file_lower.contains("occultism") {
                        mechanics.extend(vec![
                            "occultism:spirit_fire".to_string(),
                            "occultism:crushing".to_string(),
                            "occultism:ritual".to_string(),
                        ]);
                    }
                    if file_lower.contains("ars_nouveau") || file_lower.contains("arsnouveau") {
                        mechanics.extend(vec![
                            "ars_nouveau:enchanting_apparatus".to_string(),
                            "ars_nouveau:imbuement".to_string(),
                            "ars_nouveau:glyph".to_string(),
                        ]);
                    }
                    if file_lower.contains("actuallyadditions") {
                        mechanics.extend(vec![
                            "actuallyadditions:empowering".to_string(),
                            "actuallyadditions:crushing".to_string(),
                        ]);
                    }
                }
            }
        }
    }

    // 2. Recursively scan kubejs/server_scripts folder for dynamic event.recipes.<mod>.<mechanic>()
    let server_scripts_path = base_path.join("kubejs").join("server_scripts");
    if server_scripts_path.exists() && server_scripts_path.is_dir() {
        scan_directory_for_mechanics(&server_scripts_path, &mut mechanics);
    }

    // 3. Recursively scan kubejs/exported folder for items
    let exported_path = base_path.join("kubejs").join("exported");
    if exported_path.exists() && exported_path.is_dir() {
        scan_directory_for_items(&exported_path, &mut items);
    }

    // 4. Scan items from FTB Quests chapters & reward tables
    let ftb_dir = base_path.join("config").join("ftbquests").join("quests");
    if ftb_dir.exists() && ftb_dir.is_dir() {
        scan_directory_for_items(&ftb_dir, &mut items);
    }

    // 5. Scan items from KubeJS scripts
    let kubejs_dir = base_path.join("kubejs");
    if kubejs_dir.exists() && kubejs_dir.is_dir() {
        scan_directory_for_items(&kubejs_dir, &mut items);
    }

    // Deduplicate mechanics, detected_mods and items
    mechanics.sort();
    mechanics.dedup();
    detected_mods.sort();
    detected_mods.dedup();
    items.sort();
    items.dedup();

    // 6. Detect Minecraft Version and Mod Loader
    let mut detected_version = None;
    let mut detected_loader = None;

    // Check minecraftinstance.json
    let inst_json = base_path.join("minecraftinstance.json");
    if inst_json.exists() {
        if let Ok(content) = fs::read_to_string(&inst_json) {
            if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                if let Some(gv) = json.get("gameVersion").and_then(|v| v.as_array()) {
                    for item in gv {
                        if let Some(s) = item.as_str() {
                            if s.chars().next().map_or(false, |c| c.is_ascii_digit()) {
                                detected_version = Some(s.to_string());
                            } else if s.eq_ignore_ascii_case("neoforge") || s.eq_ignore_ascii_case("forge") || s.eq_ignore_ascii_case("fabric") {
                                detected_loader = Some(s.to_string());
                            }
                        }
                    }
                }
            }
        }
    }

    // Check manifest.json
    if detected_version.is_none() {
        let manifest_json = base_path.join("manifest.json");
        if manifest_json.exists() {
            if let Ok(content) = fs::read_to_string(&manifest_json) {
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                    if let Some(mc) = json.get("minecraft") {
                        if let Some(v) = mc.get("version").and_then(|v| v.as_str()) {
                            detected_version = Some(v.to_string());
                        }
                        if let Some(loaders) = mc.get("modLoaders").and_then(|v| v.as_array()) {
                            if let Some(first) = loaders.first().and_then(|l| l.get("id")).and_then(|id| id.as_str()) {
                                detected_loader = Some(first.to_string());
                            }
                        }
                    }
                }
            }
        }
    }

    // Default heuristic fallback if no metadata file
    if detected_version.is_none() {
        detected_version = Some("1.21.1".to_string());
    }
    if detected_loader.is_none() {
        detected_loader = Some("NeoForge".to_string());
    }

    Ok(SyncedData {
        items,
        mechanics,
        detected_mods,
        detected_version,
        detected_loader,
    })
}

fn parse_clean_mod_name(filename: &str) -> String {
    let mut name = filename.strip_suffix(".jar").unwrap_or(filename);
    
    // Remove typical loaders & version suffixes
    let patterns = ["-neoforge", "-forge", "-fabric", "-quilt", "+mc", "_mc", "-mc", ".neoforge", ".forge", ".fabric"];
    for p in &patterns {
        if let Some(idx) = name.to_lowercase().find(p) {
            name = &name[..idx];
        }
    }

    // Strip numbers and version digits e.g. -1.21.1-1.0.0 or _1.21
    if let Some(dash_idx) = name.find('-') {
        let after = &name[dash_idx + 1..];
        if after.chars().next().map_or(false, |c| c.is_ascii_digit()) {
            name = &name[..dash_idx];
        }
    }
    if let Some(underscore_idx) = name.find('_') {
        let after = &name[underscore_idx + 1..];
        if after.chars().next().map_or(false, |c| c.is_ascii_digit()) {
            name = &name[..underscore_idx];
        }
    }

    let cleaned = name.replace(['_', '-'], " ");
    cleaned.split_whitespace()
        .map(|word| {
            let mut c = word.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn scan_directory_for_items(dir: &Path, items: &mut Vec<String>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                scan_directory_for_items(&p, items);
            } else if p.is_file() {
                let file_name = p.file_name().unwrap_or_default().to_string_lossy().to_lowercase();
                
                // Parse JSON files (sqh_items.json, item.json, registries, etc.)
                if file_name.ends_with(".json") {
                    if let Ok(content) = fs::read_to_string(&p) {
                        if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                            extract_items_from_json(&json, items);
                        }
                    }
                }
                // Parse SNBT files (FTB Quests)
                else if file_name.ends_with(".snbt") {
                    if let Ok(content) = fs::read_to_string(&p) {
                        for word in content.split(|c: char| c.is_whitespace() || c == '"' || c == '\'' || c == '{' || c == '}' || c == '[' || c == ']' || c == ',') {
                            let trimmed = word.trim();
                            if trimmed.contains(':') && !trimmed.contains('/') && !trimmed.contains('\\') && !trimmed.starts_with("http") && trimmed.len() > 3 && trimmed.len() < 60 {
                                items.push(trimmed.to_string());
                            }
                        }
                    }
                }
                // Parse JS / TXT files
                else if file_name.ends_with(".js") || file_name.ends_with(".txt") {
                    if let Ok(content) = fs::read_to_string(&p) {
                        for word in content.split(|c: char| c.is_whitespace() || c == '"' || c == '\'' || c == '`' || c == '(' || c == ')' || c == '[' || c == ']' || c == ',' || c == ';') {
                            let trimmed = word.trim();
                            if trimmed.contains(':') && !trimmed.contains('/') && !trimmed.contains('\\') && !trimmed.starts_with("http") && trimmed.len() > 3 && trimmed.len() < 60 {
                                items.push(trimmed.to_string());
                            }
                        }
                    }
                }
            }
        }
    }
}

fn extract_items_from_json(json: &serde_json::Value, items: &mut Vec<String>) {
    match json {
        serde_json::Value::Array(arr) => {
            for val in arr {
                if let Some(s) = val.as_str() {
                    if s.contains(':') {
                        items.push(s.to_string());
                    }
                } else if val.is_object() {
                    extract_items_from_json(val, items);
                }
            }
        },
        serde_json::Value::Object(map) => {
            if let Some(items_val) = map.get("items").or_else(|| map.get("values")).or_else(|| map.get("entries")) {
                extract_items_from_json(items_val, items);
            } else {
                for (k, v) in map {
                    if k.contains(':') {
                        items.push(k.clone());
                    }
                    if let Some(s) = v.as_str() {
                        if s.contains(':') {
                            items.push(s.to_string());
                        }
                    }
                }
            }
        },
        serde_json::Value::String(s) => {
            if s.contains(':') {
                items.push(s.clone());
            }
        },
        _ => {}
    }
}

fn scan_directory_for_mechanics(dir: &Path, mechanics: &mut Vec<String>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                scan_directory_for_mechanics(&p, mechanics);
            } else if p.is_file() && p.extension().map_or(false, |e| e == "js") {
                if let Ok(content) = fs::read_to_string(&p) {
                    for line in content.lines() {
                        let trimmed = line.trim();
                        // 1. event.recipes.<mod>.<mechanic>
                        if let Some(idx) = trimmed.find("event.recipes.") {
                            let after = &trimmed[idx + 14..];
                            let token: String = after.chars().take_while(|c| c.is_alphanumeric() || *c == '.' || *c == '_').collect();
                            let parts: Vec<&str> = token.split('.').collect();
                            if parts.len() >= 2 {
                                let mod_id = parts[0];
                                let mech = parts[1];
                                if !mod_id.is_empty() && !mech.is_empty() {
                                    mechanics.push(format!("{}:{}", mod_id, mech));
                                }
                            }
                        }
                        // 2. "type": "mod:mechanic"
                        if trimmed.contains("\"type\":") || trimmed.contains("'type':") || trimmed.contains("type:") {
                            if let Some(colon) = trimmed.find(':') {
                                let val = trimmed[colon + 1..].trim().trim_matches(|c| c == '"' || c == '\'' || c == ',' || c == '`');
                                if val.contains(':') && !val.contains('/') && !val.contains('\\') && !val.starts_with("http") && val.len() < 40 {
                                    mechanics.push(val.to_string());
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

